name: Build and Release Windows Forms App

on:
  push:
    tags:
      - 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore LMS.sln

    - name: Build
      run: dotnet build LMS.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish LMS/LMS.csproj -c Release -r win-x64 --self-contained false -o publish /p:PublishSingleFile=true

    - name: Create release artifact
      uses: actions/upload-artifact@v2
      with:
        name: library-management-system
        path: publish/**

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: library-management-system
        path: ./release

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Automated release of version ${{ github.ref }}.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/publish/*
        asset_name: library-management-system.zip
        asset_content_type: application/zip
